#!/bin/bash

APACHE_CONF="$(a2info confdir)"
USER=$(whoami)

if [ $# -ne 1 ];
then
  printf "Usage: %s <domain>\n" "$(basename $0)" >&2
  exit 1
fi

DOMAIN="$1"

if [ "$USER" != root ]; then
  echo "need root privileges" >&2
  exit 5
fi

if [ ! -f "$APACHE_CONF/sites-available/$DOMAIN.conf" ]
then
  echo "No configured site for this domain." >&2
  exit 10
fi

[ -L "$APACHE_CONF/sites-enabled/$DOMAIN.conf" ] \
  && rm "$APACHE_CONF/sites-enabled/$DOMAIN.conf"

apachectl graceful