#!/bin/bash

APACHE_CONF="$(a2info confdir)"
USER=$(whoami)

if [ $# -ne 1 ];
then
  printf "Usage: %s <domain>\n" "$(basename $0)" >&2
  printf "       %s -a / --all\n" "$(basename $0)" >&2
  exit 1
fi

if [ "$USER" != root ]; then
  echo "need root privileges" >&2
  exit 5
fi

case "$1" in
  "-a" | "-all")
    for FILEPATH in "$APACHE_CONF/sites-available/"*.conf; do
      FILE=$(basename "$FILEPATH")
      [ ! -L "$APACHE_CONF/sites-enabled/$FILE" ] \
        && ln -s "$APACHE_CONF/sites-available/$FILE" \
          "$APACHE_CONF/sites-enabled/$FILE"
    done
    ;;
  *)
    DOMAIN="$1"
    if [ ! -f "$APACHE_CONF/sites-available/$DOMAIN.conf" ]
    then
      echo "No configured site for this domain." >&2
      exit 10
    fi

    [ ! -L "$APACHE_CONF/sites-enabled/$DOMAIN.conf" ] \
      && ln -s "$APACHE_CONF/sites-available/$DOMAIN.conf" \
        "$APACHE_CONF/sites-enabled/$DOMAIN.conf"
    ;;
esac


apachectl graceful