#!/bin/bash

APACHE_CONF="$(a2info confdir)"
APACHE_LOG="$(a2info logdir)"
DOCUMENT_ROOT="$(pwd)"
USER=$(whoami)
EMAIL='postmaster@localhost'
PML_CONF="$(a2info pmldir)"
SHARE_DIR="$(a2info sharedir)"

if [ $# -ne 1 ];
then
  printf "Usage: %s <domain>\n" "$(basename $0)" >&2
  exit 1
fi

DOMAIN="$1"

if [ "$USER" != root ]; then
  echo "need root privileges" >&2
  exit 5
fi

if [ -f "$APACHE_CONF/sites-available/$DOMAIN.conf" ]
then
  echo "A conf file already exist for this domain." >&2
  exit 10
fi

read -p "Separate Log Files ? [y/N]" SEPARATE_LOGS
case $SEPARATE_LOGS in
  [oOyY])
    SEPARATE_LOGS=1
    LOGFILE="ErrorLog $APACHE_LOG/$DOMAIN-error.log\n"
    LOGFILE="$LOGFILE  CustomLog $APACHE_LOG/$DOMAIN-access.log vcombined"
    ;;
  *)
    SEPARATE_LOGS=0
    LOGFILE=""
    ;;
esac

if [ "$SEPARATE_LOGS" ]; then
  cp $SHARE_DIR/pml-config/access.json $PML_CONF/$DOMAIN-access.json
  cp $SHARE_DIR/pml-config/error.json $PML_CONF/$DOMAIN-error.json
  
  ACCESS_ESCAPED="$(echo $APACHE_LOG/$DOMAIN-access.log | sed 's/\//\\\//g')"
  ERROR_ESCAPED="$(echo $APACHE_LOG/$DOMAIN-error.log | sed 's/\//\\\//g')"
  HOME_ESCAPED="$(echo $DOCUMENT_ROOT | sed 's/\//\\\//g')"

  sed -i "/{{DOMAIN}}/s//$DOMAIN/g" $PML_CONF/$DOMAIN-access.json
  sed -i "/{{PATH}}/s//$ACCESS_ESCAPED/g" $PML_CONF/$DOMAIN-access.json

  sed -i "/{{DOMAIN}}/s//$DOMAIN/g" $PML_CONF/$DOMAIN-error.json
  sed -i "/{{PATH}}/s//$ERROR_ESCAPED/g" $PML_CONF/$DOMAIN-error.json
  sed -i "/{{HOME}}/s//$HOME_ESCAPED/g" $PML_CONF/$DOMAIN-error.json
fi

echo -e "
<VirtualHost *:80>
  ServerAdmin $EMAIL
  ServerName $DOMAIN
  DocumentRoot '$DOCUMENT_ROOT'
  <Directory '$DOCUMENT_ROOT'>
    Options Indexes FollowSymLinks
    AllowOverride all
    Require all granted
  </Directory>
  $LOGFILE
</VirtualHost>
" > "$APACHE_CONF/sites-available/$DOMAIN.conf"

[ ! -L "$APACHE_CONF/sites-enabled/$DOMAIN.conf" ] \
  && ln -s "$APACHE_CONF/sites-available/$DOMAIN.conf" \
    "$APACHE_CONF/sites-enabled/$DOMAIN.conf"

# On a besoin de lire littéralement les . donc \.
grep -q "\<${DOMAIN//./\\.}\>" /etc/hosts \
  || echo "127.0.0.1  $DOMAIN" >> /etc/hosts

apachectl graceful