#!/bin/bash

APACHE_CONF="$(a2info confdir)"
APACHE_LOG="$(a2info logdir)"
DOCUMENT_ROOT="$(pwd)"
USER=$(whoami)
EMAIL='postmaster@localhost'

if [ $# -ne 1 ];
then
  printf "Usage: %s <domain>\n" "$(basename $0)" >&2
  exit 1
fi

DOMAIN="$1"

if [ "$USER" != root ]; then
  echo "need root privileges" >&2
  exit 5
fi

if [ -f "$APACHE_CONF/sites-available/$DOMAIN.conf" ]
then
  echo "A conf file already exist for this domain." >&2
  exit 10
fi

LOGFILE="ErrorLog $APACHE_LOG/$DOMAIN-error.log\n"
LOGFILE="$LOGFILE  CustomLog $APACHE_LOG/$DOMAIN-access.log vcombined"

echo -e "
<VirtualHost *:80>
  ServerAdmin $EMAIL
  ServerName $DOMAIN
  DocumentRoot '$DOCUMENT_ROOT'
  <Directory '$DOCUMENT_ROOT'>
    Options Indexes FollowSymLinks
    AllowOverride all
    Require all granted
  </Directory>
  $LOGFILE
</VirtualHost>
" > "$APACHE_CONF/sites-available/$DOMAIN.conf"

[ ! -L "$APACHE_CONF/sites-enabled/$DOMAIN.conf" ] \
  && ln -s "$APACHE_CONF/sites-available/$DOMAIN.conf" \
    "$APACHE_CONF/sites-enabled/$DOMAIN.conf"

# On a besoin de lire littéralement les . donc \.
grep -q "\<${DOMAIN//./\\.}\>" /etc/hosts \
  || echo "127.0.0.1  $DOMAIN" >> /etc/hosts

apachectl graceful