#!/bin/bash

APACHE_CONF="$(a2info confdir)"
PML_CONF="$(a2info pmldir)"
USER=$(whoami)

if [ $# -ne 1 ];
then
  printf "Usage: %s <domain>\n" "$(basename $0)" >&2
  exit 1
fi

DOMAIN="$1"

if [ ! -f "$APACHE_CONF/sites-available/$DOMAIN.conf" ]
then
  echo "No configured site for this domain." >&2
  exit 10
fi

if [ "$USER" != root ]; then
  echo "need root privileges" >&2
  exit 5
fi

[ -L "$APACHE_CONF/sites-enabled/$DOMAIN.conf" ] \
  && rm "$APACHE_CONF/sites-enabled/$DOMAIN.conf"

[ -f "$APACHE_CONF/sites-available/$DOMAIN.conf" ] \
  && rm "$APACHE_CONF/sites-available/$DOMAIN.conf"

[ -f "$PML_CONF/$DOMAIN-access.json" ] \
  && rm "$PML_CONF/$DOMAIN-access.json"

[ -f "$PML_CONF/$DOMAIN-error.json" ] \
  && rm "$PML_CONF/$DOMAIN-error.json"



# On a besoin de lire littéralement les . donc \.
# \<  \> spécifie un caractère délimitateur de fin de mot
sed -i "/\<${DOMAIN//./\\.}\>/d" /etc/hosts

apachectl graceful
