#!/bin/bash

APACHE_CONF="$(a2info confdir)"
PML_CONF="$(a2info pmldir)"
SHARE_DIR="$(a2info sharedir)"

for FILE in $PML_CONF/* ; do
  FILENAME=$(basename $FILE)
  if [[ $FILENAME == "00-common-access.json" \
    || $FILENAME == "00-common-error.json" ]]; then
      continue
  fi

  rm "$FILE"
done


for FILE in $APACHE_CONF/sites-available/* ; do
  echo $FILE

  grep -q 'CustomLog' $FILE
  if [[ $? != 0 ]]; then
    continue
  fi

  DOMAIN="$(awk '/ServerName/ { print $2}' $FILE)"
  DOCUMENT_ROOT="$(awk '/DocumentRoot/ { print $2 }' $FILE | cut -d\' -f 2)"

  ERROR_LOG_FILE="$(awk '/ErrorLog/ { print $2}' $FILE)"
  ACCESS_LOG_FILE="$(awk '/CustomLog/ { print $2}' $FILE)"

  ACCESS_ESCAPED="$(echo $ACCESS_LOG_FILE | sed 's/\//\\\//g')"
  ERROR_ESCAPED="$(echo $ERROR_LOG_FILE | sed 's/\//\\\//g')"
  HOME_ESCAPED="$(echo $DOCUMENT_ROOT | sed 's/\//\\\//g')"

  [ -f "$PML_CONF/$DOMAIN-access.json" ] \
    && rm "$PML_CONF/$DOMAIN-access.json"

  [ -f "$PML_CONF/$DOMAIN-error.json" ] \
    && rm "$PML_CONF/$DOMAIN-error.json"

  cp $SHARE_DIR/pml-config/access.json $PML_CONF/$DOMAIN-access.json
  cp $SHARE_DIR/pml-config/error.json $PML_CONF/$DOMAIN-error.json

  sed -i "/{{DOMAIN}}/s//$DOMAIN/g" $PML_CONF/$DOMAIN-access.json
  sed -i "/{{PATH}}/s//$ACCESS_ESCAPED/g" $PML_CONF/$DOMAIN-access.json

  sed -i "/{{DOMAIN}}/s//$DOMAIN/g" $PML_CONF/$DOMAIN-error.json
  sed -i "/{{PATH}}/s//$ERROR_ESCAPED/g" $PML_CONF/$DOMAIN-error.json
  sed -i "/{{HOME}}/s//$HOME_ESCAPED/g" $PML_CONF/$DOMAIN-error.json

done